#include "ASMWriter.h"

#include <cerrno>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <stdexcept>

// ---- helpers ----------------------------------------------------------------

static void write_file_if_changed(const std::string& path, const std::string& content)
{
    std::ifstream in(path, std::ios::binary);
    if (in) {
        std::string existing(std::istreambuf_iterator<char>(in), {});
        if (existing == content)
            return;
    }

    std::ofstream out(path, std::ios::binary);
    if (!out)
        throw std::runtime_error(std::string("Can't write file: ") + path + " - " + strerror(errno));
    out << content;
    if (!out)
        throw std::runtime_error(std::string("Write error: ") + path + " - " + strerror(errno));
}

// ---- public -----------------------------------------------------------------

void write_asm(const std::string& path,
               uint32_t start, uint32_t end,
               const Memory& memory,
               const LabelMap& labels)
{
    std::ostringstream out;

    out << "; Generated by DyneSect\n\n";
    out << "        AREA |C$$code|, CODE, READONLY\n";
    out << "|x$codeseg|\n\n";

    for (uint32_t addr = start; addr < end; addr += 4) {
        if (const Label* lbl = labels.find(addr)) {
            // out << lbl->name() << "\n";
            // out << "        ; 0x" << std::hex << std::setw(8) << std::setfill('0') << addr << "\n";
            out << lbl->name() << "        ; 0x" << std::hex << std::setw(8) << std::setfill('0') << addr << "\n";
        }
        uint32_t word = memory.read_word(addr);
        out << "        DCD     0x" << std::hex << std::setw(8) << std::setfill('0') << word << "\n";
    }

    out << "\n        END\n\n";

    write_file_if_changed(path, out.str());
}
