
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <stdexcept>

#include <nlohmann/json.hpp>

using json = nlohmann::json;

const std::string gConfigPath = DSECT_CONFIG_PATH;
const std::string gAIFFilePath = DSECT_DEBUG_IMAGE_PATH "/Senior CirrusNoDebug image";
const std::string gRExFilePath = DSECT_DEBUG_IMAGE_PATH "/Senior CirrusNoDebug high";
const std::string gWorkPath = DSECT_WORK_PATH "/";
const std::string gROMFilePath = DSECT_WORK_PATH "/ROM.bin";
const std::string gROMBlockFilePath = DSECT_WORK_PATH "/rom_block_";

uint8_t ROM[8*1024*1024];

// dynesect: reads the Newton AIF and REx images, analyses the ROM content,
// and writes disassembled source files for reassembly with the Norcroft toolchain.

// -DDSECT_CONFIG_PATH=${CMAKE_SOURCE_DIR}
// -DDSECT_TOOLS_PATH=/usr/local/bin
// -DDSECT_DEBUG_IMAGE_PATH=/Users/matt/dev/Newton/ROMs/MP2x00 US
// -DDSECT_DDK_INCLUDE_PATH=/Users/matt/dev/Newton/NewtonDev/NewtonDev.ux/Cpp/NCT_Projects/DDKIncludes
// -DDSECT_WORK_PATH=/Users/matt/dev/DyneSect.git/work
// Senior CirrusNoDebug image
// Senior CirrusNoDebug high

/* Just som enotes:

#!/bin/sh
echo "ARM6asm ROM/ArrayPop.gen.s -o ROM/ArrayPop.gen.o"
./bin/ARM6asm ---allin-data-utf8-to-mac ROM/ArrayPop.gen.s -o ROM/ArrayPop.gen.o
echo "ARM6asm ROM/ArrayIsEmpty.gen.s -o ROM/ArrayIsEmpty.gen.o"
./bin/ARM6asm ---allin-data-utf8-to-mac ROM/ArrayIsEmpty.gen.s -o ROM/ArrayIsEmpty.gen.o
echo "ARMLink -via link.via -bin -o rom.bin"
./bin/ARMLink -via link.via -map -bin -o rom.bin

# Ensure the ARM tools exist
if(NOT EXISTS ${BIN_DIR}/ARM6c)
    message(FATAL_ERROR "ARM6c compiler not found in ${BIN_DIR}")
endif()
if(NOT EXISTS ${BIN_DIR}/ARM6asm)
    message(FATAL_ERROR "ARM6asm assembler not found in ${BIN_DIR}")
endif()
if(NOT EXISTS ${BIN_DIR}/ARMCpp)
    message(FATAL_ERROR "ARMCpp compiler not found in ${BIN_DIR}")
endif()
if(NOT EXISTS ${BIN_DIR}/ARMLink)
    message(FATAL_ERROR "ARMLink linker not found in ${BIN_DIR}")
endif()

# Ensure that the ROM debugger files exist
if(NOT EXISTS "${RESOURCES_DIR}/Senior CirrusNoDebug image")
    message(FATAL_ERROR "'Senior CirrusNoDebug image' not found in ${RESOURCES_DIR}")
endif()
if(NOT EXISTS "${RESOURCES_DIR}/Senior CirrusNoDebug high")
    message(FATAL_ERROR "'Senior CirrusNoDebug high' not found in ${RESOURCES_DIR}")
endif()

    std::ofstream out(filename);
    out << "; Generated by NOSRescue Mulder\n\n";
    // TODO: does the code below go through ARM6asm correctly?
    // out << "        AREA |C$$data_test|,DATA\n";
    // out << "|x$dataseg|\n\n";
    out << "        AREA |C$$code|, CODE, READONLY\n";
    out << "|x$codeseg|\n\n";
    // TODO: we need to import all the symbols that we want to use
    // TODO: all symbols that *are* imported must be defined at link time, even if they are not used
    // out << "        IMPORT VEC_Length__Fl\n";
    // out << "        IMPORT VEC_GetArraySlotRef__FlT1\n";
    // out << "        IMPORT VEC_AllocateRefHandle__Fl\n";
    // out << "        IMPORT VEC_SetLength__FRC6RefVarl\n";
    // out << "        IMPORT VEC_DisposeRefHandle__FP9RefHandle\n";
    out << "Block_" << std::hex << std::setw(8) << std::setfill('0') << start << std::dec << std::setw(0) << "\n";
    for (size_t i = start; i < end; i += 4) {
        // Insert ROM address symbols as needed
        auto it = rom_symbol_list.find(i);
        if (it != rom_symbol_list.end()) {
            out << it->second->name() << "\n";
        }
        // Write word data
        uint32_t word = rom.w(i);

        if (rom.is_instruction(i)) {
            char asm_buf[128];
            int asm_len = disarm(asm_buf, static_cast<unsigned int>(i), word);
            if (asm_len > 0) {
                out << "        " << asm_buf << "\n";
            } else {
                out << "        DCD     0x" << std::hex << std::setw(8) << std::setfill('0') << word << "\n";
            }
        } else {
            out << "        DCD     0x" << std::hex << std::setw(8) << std::setfill('0') << word << "\n";
        }
    }
    out << "\n        END\n\n";
    out.close();
*/

void extract_ROM()
{
    // Read the core ROM from the AIF file.
    FILE* aif = fopen(gAIFFilePath.c_str(), "rb");
    if (!aif)
        throw std::runtime_error(std::string("Can't read AIF image file: ") + gAIFFilePath + " - " + strerror(errno));
    fseek(aif, 0x00000080, SEEK_SET);
    fread(ROM, 1, 0x0071fc4c, aif);
    fclose(aif);

    // Read ROM Extension from the REx file.
    FILE* rex = fopen(gRExFilePath.c_str(), "rb");
    if (!rex)
        throw std::runtime_error(std::string("Can't read REx image file: ") + gRExFilePath + " - " + strerror(errno));
    fread(ROM + 0x0071fc4c, 1, 0x000ce3fc, rex);
    fclose(rex);
}


void write_ROM_binary()
{
    // Just write one huge binary chunk
    FILE* rom = fopen(gROMFilePath.c_str(), "wb");
    if (!rom)
        throw std::runtime_error(std::string("Can't write ROM file: ") + gRExFilePath + " - " + strerror(errno));
    fwrite(ROM, 1, 8*1024*1024, rom);
    fclose(rom);
}


void write_rom_block(int n)
{
    // Write an assembler file that ARM6asm can translate
    std::string filename = gROMBlockFilePath + std::to_string(n) + ".s";
    FILE* out = fopen(filename.c_str(), "wb");
    if (!out)
        throw std::runtime_error(std::string("Can't write assembler monolith: ") + filename + " - " + strerror(errno));
    fprintf(out, "; Generated by DyneSect\n\n");
    // TODO: does the code below go through ARM6asm correctly?
    // out << "        AREA |C$$data_test|,DATA\n";
    // out << "|x$dataseg|\n\n";
    fprintf(out, "        AREA |C$$data_test|,DATA\n");
    fprintf(out, "|x$dataseg|\n\n");
    // out << "        AREA |C$$code|, CODE, READONLY\n";
    // out << "|x$codeseg|\n\n";

    // 0.06s / kB
    // 512kB = 33s
    // 1MB = 63s
    // 8MB does *not* finish within 10 minutes!
    // Linking of 8 1MB files takes 1.s

    // for (int i=0; i<1024; i+=4) {
    for (int i=0; i<1*1024*1024; i+=4) {
        uint8_t* src = ROM + i + (n * 1024 * 1024);
        uint32_t word = (src[0]<<24) | (src[1]<<16) | (src[2]<<8) | (src[3]);
        fprintf(out, "        DCD     0x%08x\n", word);
    }

    fprintf(out, "\n        END\n\n");

    fclose(out);
}


void write_rom_blocks()
{
    std::ifstream f(gConfigPath + "/rom_chunks.json");
    json data = json::parse(f);
    if (data.is_null())
        throw std::runtime_error(std::string("Can't read " + gConfigPath + "/rom_chunks.json"));
    json chunks = data["chunks"];
    if (!chunks.is_array())
        throw std::runtime_error(std::string("ROM Chunks.json: expected \"chunks\" array"));

    int n = chunks.size();
    for (int i=0; i<n; i++) {
        json chunk = chunks[i];
        json name = chunk["name"];
        if (!name.is_string())
            throw std::runtime_error(std::string("ROM Chunks.json: expected \"name\" in chunk" + std::to_string(i)));
        // Name ending in '/' set a new subdirectory
        // Name ending in '.s' is an ARM32 assembler file
        // Name ending in '.c' is a C file
        // Name ending in '.cpp' is C++ file
        write_rom_block(i);
    }
}


int main(int argc, char *argv[])
{
    std::cout << "dynesect: Newton ROM dissection tool\n";

    extract_ROM();
    write_ROM_binary();
    write_rom_blocks();

    return 0;
}
