
#include "main.h"

#include "AIFReader.h"
#include "RExReader.h"

#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <string_view>
#include <stdexcept>

#include <nlohmann/json.hpp>

using json = nlohmann::json;

const std::string gConfigPath = DSECT_CONFIG_PATH;
const std::string gAIFFilePath = DSECT_DEBUG_IMAGE_PATH "/Senior CirrusNoDebug image";
const std::string gRExFilePath = DSECT_DEBUG_IMAGE_PATH "/Senior CirrusNoDebug high";
const std::string gWorkPath = DSECT_WORK_PATH "/";
const std::string gROMFilePath = DSECT_WORK_PATH "/ROM.bin";

Memory gMem;
LabelMap gLabelMap;

// dynesect: reads the Newton AIF and REx images, analyses the ROM content,
// and writes disassembled source files for reassembly with the Norcroft toolchain.

// -DDSECT_CONFIG_PATH=${CMAKE_SOURCE_DIR}
// -DDSECT_TOOLS_PATH=/usr/local/bin
// -DDSECT_DEBUG_IMAGE_PATH=/Users/matt/dev/Newton/ROMs/MP2x00 US
// -DDSECT_DDK_INCLUDE_PATH=/Users/matt/dev/Newton/NewtonDev/NewtonDev.ux/Cpp/NCT_Projects/DDKIncludes
// -DDSECT_WORK_PATH=/Users/matt/dev/DyneSect.git/work
// Senior CirrusNoDebug image
// Senior CirrusNoDebug high

/* Just som enotes:
#!/bin/sh
echo "ARMLink -via link.via -bin -o rom.bin"
./bin/ARMLink -via link.via -map -bin -o rom.bin
*/

void extract_ROM()
{
    gMem.add_allocated_block(0x00000000, 0x00800000);

    // Read the core ROM from the AIF file.
    uint32_t core_end = read_aif(gAIFFilePath, gMem, gLabelMap);

    // Read the ROM Extension.
    read_rex(gRExFilePath, core_end, gMem, gLabelMap);
    // ROM: 0..0071a95c End of RW: 0071fc4c
}


void write_ROM_binary()
{
    // Just write one huge binary chunk
    FILE* rom = fopen(gROMFilePath.c_str(), "wb");
    if (!rom)
        throw std::runtime_error(std::string("Can't write ROM file: ") + gRExFilePath + " - " + strerror(errno));
    fwrite(gMem.block_at(0x00000000)->data(), 1, 8*1024*1024, rom);
    fclose(rom);
}

/**
 * Writes content to a file only if the file does not exist or its current
 * content differs. Preserving the modification timestamp when nothing has
 * changed prevents the Norcroft assembler from reprocessing unchanged blocks.
 */
void write_file_if_changed(const std::string& path, const std::string& content)
{
    std::ifstream in(path, std::ios::binary);
    if (in) {
        std::string existing(std::istreambuf_iterator<char>(in), {});
        if (existing == content)
            return;
    }

    std::ofstream out(path, std::ios::binary);
    if (!out)
        throw std::runtime_error(std::string("Can't write file: ") + path + " - " + strerror(errno));
    out << content;
    if (!out)
        throw std::runtime_error(std::string("Write error: ") + path + " - " + strerror(errno));
}

void write_asm_chunk(const std::string& name, int start, int end)
{
    //      .text
    //      .org    0
    //      .word   0x12345678
    //      .fill   n, size, value
    //      .end

    std::ostringstream out;
    out << "; Generated by DyneSect\n\n";
    // TODO: does the code below go through ARM6asm correctly?
    // out << "        AREA |C$$data_test|,DATA\n";
    // out << "|x$dataseg|\n\n";
    out << "        AREA |C$$data_test|,DATA\n";
    out << "|x$dataseg|\n\n";
    // out << "        AREA |C$$code|, CODE, READONLY\n";
    // out << "|x$codeseg|\n\n";
    // out << "        IMPORT VEC_Length__Fl\n";

    // 0.06s / kB
    // 512kB = 33s
    // 1MB = 63s
    // 8MB does *not* finish within 10 minutes!
    // Linking of 8 1MB files takes 1.s

    for (int i=start; i<end; i+=4) {
        uint32_t word = gMem.read_word(i);
        out << "        DCD     0x" << std::hex << std::setw(8) << std::setfill('0') << word << "\n";
    }

    out << "\n        END\n\n";

    write_file_if_changed(gWorkPath + name, out.str());
}


void write_rom_blocks()
{
    std::ifstream f(gConfigPath + "/rom_chunks.json");
    json data = json::parse(f);
    if (data.is_null())
        throw std::runtime_error(std::string("Can't read " + gConfigPath + "/rom_chunks.json"));
    json chunks = data["chunks"];
    if (!chunks.is_array())
        throw std::runtime_error(std::string("ROM Chunks.json: expected \"chunks\" array"));

    int n = chunks.size();
    int chunk_start = 0;
    int chunk_end = 0x00800000;
    for (int i=0; i<n; i++) {
        json chunk = chunks[i];
        json name = chunk["name"];
        if (!name.is_string())
            throw std::runtime_error(std::string("ROM Chunks.json: expected \"name\" in chunk" + std::to_string(i)));
        std::string chunk_name = name;
        if (chunk_name.ends_with("/")) {
            // Set folder
        } else {
            json end = chunk["end"];
            if (!end.is_string())
                throw std::runtime_error(std::string("ROM Chunks.json: expected \"last\" in chunk" + std::to_string(i)));
            chunk_end = std::stoul((std::string)end, nullptr, 0);
            if (chunk_name.ends_with(".s")) {
                // ARM32 assembler
                write_asm_chunk(chunk_name, chunk_start, chunk_end);
            } else if (chunk_name.ends_with(".c")) {
                // C code
            } else if (chunk_name.ends_with(".cpp")) {
                // C++ code
            }
            chunk_start = chunk_end;
        }
    }
}


int main(int argc, char *argv[])
{
    std::cout << "dynesect: Newton ROM dissection tool\n";

    extract_ROM();
    write_ROM_binary();
    write_rom_blocks();

    return 0;
}
